### ISSUE TITLE
nuget restore fail ,how to fix

### ISSUE THREAD

**Issue by jonesyeh** [sixeyed/docker-on-windows#6]
Step 4/16 : RUN nuget restore packages.config -PackagesDirectory ..\packages
 ---> Running in e3433b4bdf8f
Restoring NuGet package Microsoft.AspNet.WebApi.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.Client.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.Core.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.WebHost.5.2.3.
Restoring NuGet package Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0.
Restoring NuGet package Newtonsoft.Json.6.0.4.
WARNING: Unable to find version '5.2.3' of package 'Microsoft.AspNet.WebApi.Client'.
  C:\Users\ContainerAdministrator\.nuget\packages\: Package 'Microsoft.AspNet.WebApi.Client.5.2.3' is not found on source 'C:\Users\ContainerAdministrator\.nuget\packages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote name could not be resolved: 'api.nuget.org'

**Comment by sixeyed** [comment]
This looks like a network issue - the container can't get out to the NuGet API. It could be a temporary network outage, so running the command again should work. If not then it could be because of a network proxy - [this is how to configure Docker to use your proxy](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#proxy-configuration).
